### ISSUE TITLE
Impedir que valores maiores com mais de 2 dígitos possam ser digitados nos valores das dezenas

### ISSUE THREAD

**Issue by AdamsEric** [AdamsEric/Loto#19]
### Contextualização:

- Atualmente, o formulário possui um comportamento de, quando o segundo dígito do campo é inserido, o cursor é apontado para o campo seguinte, para facilitar a digitação.
- Caso o usuário retorne a um campo já digitado, o sistema está permitindo que seja preenchido mais de dois caracteres
_Detalhe: é validado que o caractere existe caractere inválido na digitação, porém o ideal é impedir que isso ocorra já durante a digitação_

![image](https://github.com/AdamsEric/Loto/assets/9133966/da5a5c3d-3922-433d-a7d3-a42336225432)

### O que fazer:

- Tratar para que os campos das dezenas (tanto do concurso quanto da aposta) não permitam mais de 2 caracteres
_Atenção quanto ao campo do número do concurso: este não deve ser limitado_
_**Importante**: o comportamento de mover o cursor para o outro campo deve ser mantido._

**Comment by jhonatacaiob** [comment]
@AdamsEric Implementei a solução neste [pull request](https://github.com/AdamsEric/Loto/pull/21)
